import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';

export const getStyles = (theme: GrafanaTheme2) => ({
  root: css({
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: theme.colors.background.canvas,
  }),
  toolbar: css({
    padding: `${theme.spacing(1.5)} ${theme.spacing(2)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1),
    flexShrink: 0,
    background: theme.colors.background.primary,
  }),
  toolbarTopRow: css({
    display: 'flex',
    gap: theme.spacing(1),
    alignItems: 'center',
  }),
  pageTitle: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.h5.fontSize,
    color: theme.colors.text.primary,
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
  }),
  divider: css({
    width: '1px',
    height: '20px',
    background: theme.colors.border.medium,
    flexShrink: 0,
    margin: `0 ${theme.spacing(0.5)}`,
  }),
  dsSelect: css({ width: '148px', flexShrink: 0 }),
  timePickerWrap: css({
    display: 'inline-flex',
    '& > button': {
      background: theme.colors.background.secondary,
      border: `1px solid ${theme.colors.border.medium}`,
      borderRadius: theme.shape.radius.default,
      padding: `0 ${theme.spacing(1)}`,
      height: '32px',
      '&:hover': {
        background: theme.colors.action.hover,
        border: `1px solid ${theme.colors.border.strong}`,
      },
    },
  }),
  queryEditorWrap: css({
    // Reset some of Grafana's query editor padding so it fits our toolbar
    '& .query-editor-row': { padding: 0 },
    flex: 1,
  }),
  body: css({
    display: 'flex',
    overflow: 'hidden',
    // height is set by useLayoutEffect: window.innerHeight minus the fixed nav above the plugin
  }),
  traceList: css({
    overflow: 'auto',
    overscrollBehavior: 'contain',
    flexShrink: 0,
    background: theme.colors.background.primary,
  }),
  resizeHandle: css({
    width: '5px',
    flexShrink: 0,
    cursor: 'col-resize',
    position: 'relative',
    userSelect: 'none',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: '2px',
      width: '1px',
      background: theme.colors.border.weak,
    },
    '&:hover::after': {
      background: theme.colors.primary.border,
      width: '2px',
      left: '1.5px',
    },
  }),
  traceListHeader: css({
    padding: `${theme.spacing(0.75)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.medium}`,
    background: theme.colors.background.secondary,
    fontSize: '11px',
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    position: 'sticky',
    top: 0,
    zIndex: 1,
  }),
  traceItem: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    cursor: 'pointer',
    '&:hover': { background: theme.colors.action.hover },
    '&:hover .copy-btn': { visibility: 'visible' },
  }),
  traceItemSelected: css({
    background: `${theme.colors.primary.transparent} !important`,
    borderLeft: `3px solid ${theme.colors.primary.main}`,
  }),
  traceItemInConversation: css({
    paddingLeft: theme.spacing(3),
  }),
  conversationHeader: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    padding: `${theme.spacing(0.5)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
    background: theme.colors.background.secondary,
    fontSize: '11px',
    color: theme.colors.text.secondary,
  }),
  conversationId: css({
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  traceName: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.text.primary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginBottom: '2px',
  }),
  traceMeta: css({
    display: 'flex',
    gap: theme.spacing(1),
    fontSize: '11px',
    color: theme.colors.text.secondary,
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
  traceService: css({
    color: theme.colors.text.link,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  copyBtn: css({
    visibility: 'hidden',
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    '&:hover': { color: theme.colors.text.primary },
  }),
  detailArea: css({
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  }),
  empty: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
    color: theme.colors.text.secondary,
  }),
  skeletonItem: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    borderBottom: `1px solid ${theme.colors.border.weak}`,
  }),
  skeletonLine: css({
    borderRadius: '3px',
    background: `linear-gradient(90deg, ${theme.colors.background.secondary} 25%, ${theme.colors.action.hover} 50%, ${theme.colors.background.secondary} 75%)`,
    backgroundSize: '200% 100%',
    animation: 'shimmer 1.4s infinite linear',
    '@keyframes shimmer': {
      '0%': { backgroundPosition: '200% 0' },
      '100%': { backgroundPosition: '-200% 0' },
    },
  }),
  emptyTitle: css({
    fontSize: theme.typography.h5.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.primary,
  }),
  emptySubtitle: css({
    fontSize: theme.typography.bodySmall.fontSize,
    maxWidth: '320px',
    textAlign: 'center',
  }),
});
