import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';

export const getStyles = (theme: GrafanaTheme2) => ({
  container: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
    padding: theme.spacing(1.5),
  }),
  sectionStack: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
  }),
  headerRow: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    flexWrap: 'wrap',
  }),
  modelBadge: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    padding: `${theme.spacing(0.5)} ${theme.spacing(1.25)}`,
    background: theme.colors.background.secondary,
    borderRadius: theme.shape.radius.default,
    border: `1px solid ${theme.colors.border.medium}`,
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.body.fontSize,
  }),
  modelIcon: css({
    color: theme.colors.warning.text,
  }),
  kindBadge: css({
    fontSize: '11px',
    padding: `2px ${theme.spacing(0.75)}`,
    borderRadius: theme.shape.radius.default,
    fontWeight: theme.typography.fontWeightMedium,
    color: '#fff',
    letterSpacing: '0.02em',
  }),
  conventionBadge: css({
    fontSize: '11px',
    padding: `2px ${theme.spacing(0.75)}`,
    borderRadius: theme.shape.radius.default,
    background: theme.colors.background.secondary,
    color: theme.colors.text.secondary,
    border: `1px solid ${theme.colors.border.weak}`,
  }),
  section: css({
    border: `1px solid ${theme.colors.border.medium}`,
    borderRadius: theme.shape.radius.default,
    overflow: 'hidden',
  }),
  sectionHeader: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    padding: `${theme.spacing(0.75)} ${theme.spacing(1.5)}`,
    cursor: 'pointer',
    userSelect: 'none',
    background: theme.colors.background.secondary,
    border: 'none',
    width: '100%',
    color: theme.colors.text.primary,
    font: 'inherit',
    textAlign: 'left',
    '&:hover': {
      background: theme.colors.action.hover,
    },
  }),
  sectionTitle: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  sectionContent: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)} ${theme.spacing(1.5)}`,
  }),
  messagesContainer: css({
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.75),
  }),
  finishCard: css({
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
    padding: `${theme.spacing(0.75)} ${theme.spacing(1)}`,
    border: `1px solid ${theme.colors.border.medium}`,
    borderRadius: theme.shape.radius.default,
    background: theme.colors.background.secondary,
  }),
  finishCardLabel: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.bodySmall.fontSize,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  }),
  finishCardReasons: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
    marginLeft: 'auto',
  }),
  finishCardReason: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
  }),
  finishCardChoice: css({
    fontSize: '11px',
    color: theme.colors.text.secondary,
  }),
  message: css({
    border: `1px solid ${theme.colors.border.weak}`,
    borderRadius: theme.shape.radius.default,
    overflow: 'hidden',
  }),
  messageHeader: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${theme.spacing(0.5)} ${theme.spacing(1)}`,
    cursor: 'pointer',
    userSelect: 'none',
    background: 'none',
    border: 'none',
    width: '100%',
    color: 'inherit',
    font: 'inherit',
    textAlign: 'left',
  }),
  messageHeaderLeft: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
  }),
  roleLabel: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontSize: theme.typography.bodySmall.fontSize,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  }),
  messageContent: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: theme.typography.bodySmall.fontSize,
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    borderTop: `1px solid ${theme.colors.border.weak}`,
    color: theme.colors.text.primary,
  }),
  roleSystem: css({
    background: theme.isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)',
  }),
  roleUser: css({
    background: theme.isDark ? 'rgba(114,195,255,0.08)' : 'rgba(60,120,200,0.06)',
  }),
  roleAssistant: css({
    background: theme.isDark ? 'rgba(132,90,255,0.1)' : 'rgba(123,97,255,0.07)',
  }),
  roleTool: css({
    background: theme.isDark ? 'rgba(80,200,120,0.1)' : 'rgba(55,170,90,0.07)',
  }),
  tokenRow: css({
    display: 'flex',
    gap: theme.spacing(2.5),
    flexWrap: 'wrap',
    paddingTop: theme.spacing(0.5),
  }),
  tokenItem: css({
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  tokenLabel: css({
    color: theme.colors.text.secondary,
  }),
  tokenValue: css({
    fontWeight: theme.typography.fontWeightMedium,
    fontFamily: theme.typography.fontFamilyMonospace,
    color: theme.colors.text.primary,
  }),
  paramsGrid: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: `${theme.spacing(0.5)} ${theme.spacing(2)}`,
    fontSize: theme.typography.bodySmall.fontSize,
    paddingTop: theme.spacing(0.5),
  }),
  paramItem: css({
    display: 'flex',
    gap: theme.spacing(0.5),
  }),
  paramKey: css({
    color: theme.colors.text.secondary,
  }),
  paramValue: css({
    fontFamily: theme.typography.fontFamilyMonospace,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  toolMetaRow: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: `${theme.spacing(1)} ${theme.spacing(2)}`,
    marginBottom: theme.spacing(1),
    paddingBottom: theme.spacing(1),
    borderBottom: `1px solid ${theme.colors.border.weak}`,
  }),
  toolMetaItem: css({
    display: 'flex',
    gap: theme.spacing(0.5),
    fontSize: theme.typography.bodySmall.fontSize,
  }),
  toolMetaKey: css({
    color: theme.colors.text.secondary,
    fontWeight: theme.typography.fontWeightMedium,
  }),
  toolMetaValue: css({
    fontFamily: theme.typography.fontFamilyMonospace,
    color: theme.colors.text.primary,
  }),
  toolCardBlock: css({
    padding: theme.spacing(1),
    background: theme.colors.background.secondary,
    borderRadius: theme.shape.radius.default,
    border: `1px solid ${theme.colors.border.weak}`,
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: theme.typography.bodySmall.fontSize,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: 1.65,
    color: theme.colors.text.primary,
    maxHeight: '400px',
    overflow: 'auto',
  }),
  emptyContent: css({
    color: theme.colors.text.disabled,
    fontStyle: 'italic',
  }),
  markdownContent: css({
    padding: `${theme.spacing(1)} ${theme.spacing(1.5)}`,
    fontSize: theme.typography.bodySmall.fontSize,
    lineHeight: 1.65,
    wordBreak: 'break-word',
    borderTop: `1px solid ${theme.colors.border.weak}`,
    color: theme.colors.text.primary,
    '& h1, & h2, & h3, & h4': {
      color: theme.colors.text.primary,
      fontWeight: theme.typography.fontWeightMedium,
      marginTop: theme.spacing(1),
      marginBottom: theme.spacing(0.5),
    },
    '& p': { margin: `${theme.spacing(0.5)} 0` },
    '& ul, & ol': { paddingLeft: theme.spacing(2.5), margin: `${theme.spacing(0.5)} 0` },
    '& li': { marginBottom: theme.spacing(0.25) },
    '& code': {
      background: theme.colors.background.secondary,
      borderRadius: '3px',
      padding: '0 4px',
      fontFamily: theme.typography.fontFamilyMonospace,
      fontSize: '0.9em',
    },
    '& pre': {
      background: theme.colors.background.secondary,
      borderRadius: theme.shape.radius.default,
      padding: theme.spacing(1),
      overflow: 'auto',
      '& code': { background: 'none', padding: 0 },
    },
    '& blockquote': {
      borderLeft: `3px solid ${theme.colors.border.medium}`,
      paddingLeft: theme.spacing(1),
      margin: `${theme.spacing(0.5)} 0`,
      color: theme.colors.text.secondary,
    },
    '& a': { color: theme.colors.text.link },
    '& hr': { border: 'none', borderTop: `1px solid ${theme.colors.border.weak}`, margin: `${theme.spacing(1)} 0` },
    '& table': { borderCollapse: 'collapse', width: '100%', fontSize: '0.9em' },
    '& th, & td': { border: `1px solid ${theme.colors.border.weak}`, padding: `${theme.spacing(0.25)} ${theme.spacing(0.75)}` },
    '& th': { background: theme.colors.background.secondary },
  }),
  mdToggle: css({
    background: 'none',
    border: `1px solid ${theme.colors.border.weak}`,
    borderRadius: '3px',
    cursor: 'pointer',
    color: theme.colors.text.secondary,
    fontSize: '10px',
    padding: '1px 5px',
    lineHeight: 1.4,
    '&:hover': { color: theme.colors.text.primary, borderColor: theme.colors.border.medium },
  }),
  mdToggleActive: css({
    background: theme.colors.primary.transparent,
    border: `1px solid ${theme.colors.primary.border}`,
    color: theme.colors.primary.text,
  }),
  valueBlock: css({
    fontFamily: theme.typography.fontFamilyMonospace,
    fontSize: theme.typography.bodySmall.fontSize,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: 1.65,
    color: theme.colors.text.primary,
    padding: theme.spacing(0.5),
  }),
  fieldLabel: css({
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: theme.typography.fontWeightMedium,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing(0.5),
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  }),
  fieldBlock: css({
    marginBottom: theme.spacing(1),
    '&:last-child': { marginBottom: 0 },
  }),
  documentBlock: css({
    padding: theme.spacing(1),
    background: theme.colors.background.secondary,
    borderRadius: theme.shape.radius.default,
    border: `1px solid ${theme.colors.border.weak}`,
    marginBottom: theme.spacing(0.75),
    '&:last-child': { marginBottom: 0 },
  }),
  documentMeta: css({
    fontSize: '11px',
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing(0.5),
    fontFamily: theme.typography.fontFamilyMonospace,
  }),
});
